name: "Generate API doc and publish to GitHub Pages"

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

# This allows a subsequently queued workflow run to interrupt previous runs.
# github.workflow is the name of the workflow.
#   If the workflow file doesn't specify a name,
#   the value of this property is the full path of the workflow
#   file in the repository.
# github.head_ref is source branch of a pull_request
# github.ref is the pushed branch or the branch of
#   a manual run (the workflow_dispatch event)
concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-api-doc:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo concurrency group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
          echo github.workflow: ${{ github.workflow }}
          echo github.event_name: ${{ github.event_name }}
          echo github.event.pull_request.head.label: ${{ github.event.pull_request.head.label }}
          echo github.head_ref: ${{ github.head_ref }}
          echo github.ref: ${{ github.ref }}
          echo github.ref_name: ${{ github.ref_name }}

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          path: ${{ github.workspace }}/docker-home/cl-plus-ssl

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          repository: avodonosov/package-doc-dump
          ref: master
          path: ${{ github.workspace }}/docker-home/package-doc-dump

      - name: List files in the repository
        run: |
          pwd
          ls ${{ github.workspace }}/docker-home/

      - run: |
          docker run -u "$(id -u):$(id -g)" -i --mount type=bind,source=${{ github.workspace }}/docker-home,target=/home/cl/ clfoundation/cl-devel:2022-02-09 unpack-default-home-dir

      - run: |    
          docker run -u "$(id -u):$(id -g)" -i --mount type=bind,source=${{ github.workspace }}/docker-home,target=/home/cl/ clfoundation/cl-devel:2022-02-09 -q ccl --load /home/cl/cl-plus-ssl/.github/workflows/api-doc.lisp

      - name: List files in the repository
        run: |
          pwd
          ls ${{ github.workspace }}/docker-home/

      - name: prepare GitHub Pages content directory
        run: |
          mkdir ${{ github.workspace }}/github-pages/
          cp ${{ github.workspace }}/docker-home/cl-plus-ssl/index.html ${{ github.workspace }}/github-pages/
          cp ${{ github.workspace }}/docker-home/cl-plus-ssl-api.html ${{ github.workspace }}/github-pages/

      - name: Package and upload GitHub Pages artifact
        # runs only for master brach push or workflow_dispatch
        if: ${{ 'master' == github.ref_name }}
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ github.workspace }}/github-pages


  deploy:
    # runs only for master brach push or workflow_dispatch
    if: ${{ 'master' == github.ref_name }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-api-doc
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
