name: 'Test cl+ssl'


on:
  workflow_dispatch:
  push:
  pull_request:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true


jobs:
  test-cl-plus-ssl:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          pwd
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - run: |
          pwd
          docker run -i --mount type=bind,source=${{ github.workspace }},target=/home/cl/cl-plus-ssl/ avodonosov/cl-plus-ssl:latest ls /home/cl/
      - run: |
          docker run -i --mount type=bind,source=${{ github.workspace }},target=/home/cl/cl-plus-ssl/ avodonosov/cl-plus-ssl:latest ls /home/cl/cl-plus-ssl
      - run: |
          docker run -e "OPENSSL_RELEASES_BIN_DIR=/home/cl/openssl-releases/bin" -e "LIB_LOAD_MODE=new" -e "OPENSSL=openssl-1.1.1f" -e "BITS=64" -i --mount type=bind,source=${{ github.workspace }},target=/home/cl/cl-plus-ssl/ avodonosov/cl-plus-ssl:latest /home/cl/cl-plus-ssl/test/run-for-ci.sh
